id = "vibescript"
name = "Vibescript"
description = "Vibescript language support with syntax highlighting and LSP."
version = "0.0.1"
schema_version = 1
authors = ["Mauricio Gomes <mgomes@mgomes.com>"]
repository = "https://github.com/mgomes/zed-vibescript"

[grammars.vibescript]
repository = "https://github.com/mgomes/tree-sitter-vibescript"
commit = "e6d83b0c758c0f09be8b59f86310bd1eaa7f5215"

[language_servers.vibes-lsp]
name = "Vibes LSP"
language = "Vibescript"
