id = "vibescript"
name = "Vibescript"
description = "Vibescript language support with syntax highlighting and LSP."
version = "0.0.1"
schema_version = 1
authors = ["Mauricio Gomes <mauricio@edge14.com>"]
repository = "https://github.com/mgomes/zed-vibescript"

[grammars.vibescript]
repository = "https://github.com/mgomes/tree-sitter-vibescript"
commit = "4937f02cdf504c2134524710ef4d006e5631f876"

[language_servers.vibes-lsp]
name = "Vibes LSP"
language = "Vibescript"
